In [1]:
import numpy as np
import pandas as pd

# EDA
import matplotlib.pyplot as plt
import seaborn as sns

# Learning algorithms
import sklearn
from sklearn.linear_model import *

from pycaret.regression import *
from Processor import *

import warnings
warnings.filterwarnings('ignore')

import datetime
today = str(datetime.datetime.now().date()).replace("-","")
print("오늘 날짜 : " + today)

오늘 날짜 : 20210602

In [2]:
preprocessor = Preprocessor('../data/train.csv', '../data/test.csv')
X_trains, y_trains, means, stds = preprocessor.train_preprocess()
X_tests = preprocessor.test_preprocess(means, stds)

In [3]:
train_datas = []

for X_train, y_train in zip(X_trains, y_trains):
    X_train["answer"] = y_train
    train_datas.append(X_train)

In [5]:
clf = setup(data=train_datas[5], target='answer', train_size=0.8, use_gpu=True, verbose = False)

Text(value="Following data types have been inferred automatically, if they are correct press enter to continue…

                   Data Type
temperature          Numeric
windspeed            Numeric
humidity             Numeric
precipitation        Numeric
insolation           Numeric
hour                 Numeric
weekday          Categorical
min_temperature      Numeric
THI                  Numeric
mean_THI             Numeric
CDH                  Numeric
mean_CDH             Numeric
date_num             Numeric
answer                 Label

In [6]:
def SMAPE(true, pred):
    return np.mean((np.abs(true - pred)) / (np.abs(true) + np.abs(pred))) * 100

add_metric('smape', 'SMAPE', SMAPE, greater_is_better=False)

Name                                                       SMAPE
Display Name                                               SMAPE
Score Function            <function SMAPE at 0x0000021CB9E39040>
Scorer               make_scorer(SMAPE, greater_is_better=False)
Target                                                      pred
Args                                                          {}
Greater is Better                                          False
Custom                                                      True
Name: smape, dtype: object

In [7]:
best2 = compare_models(sort='SMAPE', n_select=2)

In [9]:
rf = create_model('rf')

In [10]:
tuned = tune_model(rf)

In [11]:
tuned.decision_path

<bound method BaseForest.decision_path of RandomForestRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mae',
                      max_depth=7, max_features=1.0, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.3,
                      min_impurity_split=None, min_samples_leaf=4,
                      min_samples_split=7, min_weight_fraction_leaf=0.0,
                      n_estimators=290, n_jobs=-1, oob_score=False,
                      random_state=1757, verbose=0, warm_start=False)>